name: Build linux:rockusb

on:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: cargo install --root . rockusb --example rockusb

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: rockusb-linux-amd64
        path: ./bin/rockusb
