name: Build rkdeveloptool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y libudev-dev libusb-1.0-0-dev dh-autoreconf pkg-config libusb-1.0 build-essential git wget


    - name: Clone rkdeveloptool
      run: git clone https://github.com/rockchip-linux/rkdeveloptool

    - name: Apply patches and build for x86_64
      run: |
        cd rkdeveloptool
        wget https://patch-diff.githubusercontent.com/raw/rockchip-linux/rkdeveloptool/pull/73.patch
        wget https://patch-diff.githubusercontent.com/raw/rockchip-linux/rkdeveloptool/pull/85.patch
        git am *.patch
        autoreconf -i
        ./configure
        make -j $(nproc)

    - name: Upload build outputs
      uses: actions/upload-artifact@v3
      with:
        name: rkdeveloptool
        path: |
          rkdeveloptool/rkdeveloptool
